POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_DIR_HOME_BACKGROUND=005
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=005
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=$'%K{002}%F{000} %% %f%F{002}%k\ue0b0%f '
DEFAULT_USER="$USER"

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel9k/powerlevel9k"

plugins=(gitfast)

source $ZSH/oh-my-zsh.sh

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
